"""empty message

Revision ID: 0978f1beb70d
Revises: fc88b1a68fc6
Create Date: 2018-11-18 16:44:32.539272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0978f1beb70d'
down_revision = 'fc88b1a68fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('title', sa.String(length=140), nullable=True))
    op.create_unique_constraint(None, 'post', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_column('post', 'title')
    op.drop_column('post', 'created')
    # ### end Alembic commands ###
