"""user table

Revision ID: 9f802ae70d30
Revises: 
Create Date: 2018-11-07 15:27:20.045740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f802ae70d30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('u_ser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_u_ser_email'), 'u_ser', ['email'], unique=True)
    op.create_index(op.f('ix_u_ser_username'), 'u_ser', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_u_ser_username'), table_name='u_ser')
    op.drop_index(op.f('ix_u_ser_email'), table_name='u_ser')
    op.drop_table('u_ser')
    # ### end Alembic commands ###
